### PR TITLE
Minor fixes to Spanish translation

### PR DESCRIPTION
**Pull request by ciencia**

### CODE REVIEW

**Comment by kulttuuri** [comment]
Translation files are now in new format, so parameters are %1, %2 ... instead of %s. Could you provide these fixes to new file? :)

**Comment by kulttuuri** [comment]
Thank you! FYI; I have manually applied the changes to ES file. Closing this PR.

**Comment by ciencia** [comment]
Thanks! I had a busy week and couldn't review it

**Comment by lens0021** [comment]
(FYI) Translations on translatewiki.net now are available, Visit https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-discordnotifications&language=es for details

**Pull request closed without merging**
