### PR TITLE
Change Content-type for file_get_contents

### PR DESCRIPTION
**Pull request by lens0021**
I don't know exactly what happened: Suddenly, DiscordNotifications did not work for me and this patch has fixed that.

### CODE REVIEW

**Comment by kulttuuri** [comment]
You are using the file_get_contents method instead of curl, right?

**Comment by lens0021** [comment]
Yes, `LocalSettings.php` of the wiki I working on is here: https://github.com/femiwiki/docker-mediawiki/blob/3c0ce11/configs/LocalSettings.php#L403-L414

**Comment by kulttuuri** [comment]
Right. I think that Discord pulled the plug on formdata submissions on their API or have some problem with it. I found [this](https://api.slack.com/changelog/2017-10-keeping-up-with-the-jsons) article on the subject.

Although, I think that this is also a good change as I think that json submissions are better that formdata. Could you also try that file upload, article created / removed / edited and permission changes all work fine and send correct message to Discord? And also that the user / article links work inside Discord? Just to verify that this change does not break any of this functionality :)

**Comment by kulttuuri** [comment]
Whoops - that was a Slack webhook article :D Trying to find any information related to discord...

**Comment by kulttuuri** [comment]
Yep, Discord recommends using json type for normal webhook submissions: https://discordapp.com/developers/docs/resources/webhook#execute-webhook

As we do not upload any files, I think this is a good change. It could also be that the normal formdata submission still would go through but x-www-form-urlencoded does not.

**Comment by lens0021** [comment]
I has tested below

- article creation / editing / moving / removing
- flow comment submission / editing
- user blocking / unblocking
- permission change
- and links on notifications 

image

looks good to me.

**Comment by kulttuuri** [comment]
Thank you! Merging.

**Pull request merged**
