### PR TITLE
french translation review

### PR DESCRIPTION
**Pull request by Linedwell**
Reviewed french tranlation with minor fixes.

Changes have already been reported to translatewiki too.

### CODE REVIEW

**Comment by lens0021** [comment]
It seems committed by the bot as https://github.com/kulttuuri/DiscordNotifications/commit/db38bdfb87ea860456fba32c06ebccd01410e8c2

**Comment by kulttuuri** [comment]
So sorry, missed this PR! Is this still good to go? :)

**Comment by kulttuuri** [comment]
@Linedwell ^

**Comment by kulttuuri** [comment]
@lens0021 @Linedwell this PR can be removed? Already committed by the translatewiki?

**Comment by kulttuuri** [comment]
Closing due to inactivity.

**Pull request closed without merging**
